### PR TITLE
Ruby 3 support

### PR DESCRIPTION
**Pull request by MarkusHarmsen**
This pull requests adds ruby 3 support.

### CODE REVIEW

**Comment by MarkusHarmsen** [comment]
Ah good catch!
Added ruby 3 and skipped the ruby 3 / Rails 5.2 combination.

**Comment by MarkusHarmsen** [comment]
Strange, I didn't touch them in my PR initially - gave them an update and now all have the bumped version in place.

**Comment by grosser** [comment]
bug when bumping versions :D

**Comment by grosser** [comment]
1.8.0

**Pull request merged**
