### PR TITLE
Add support for `Rails ~> 7.1`

### PR DESCRIPTION
**Pull request by viralpraxis**
Rails 7.1 was releases recently; seems like nothing breaks.

### CODE REVIEW

**Comment by grosser** [comment]
looks like deprecations need to be allowed
```
RuntimeError:
  DEPRECATION WARNING: Calling behavior= on ActiveSupport::Deprecation is deprecated and will be removed from Rails (use Rails.application.deprecators.behavior= instead) (called from <top (required)> at soft_deletion/spec/spec_helper.rb:10)
```
... and since we don't have rails that crashes

**Comment by grosser** [comment]
https://github.com/grosser/soft_deletion/pull/53

**Comment by viralpraxis** [comment]
Seems like `ActiveSupport::Deprecation.{behaviour=,silenced=} `were deprecated in **v7.1.0.beta1**, I guess

```ruby
ActiveRecord.deprecator.behavior = lambda { |message, _callback| raise message }
ActiveRecord.deprecator.silenced = false
```

would do the trick? @grosser

**Comment by grosser** [comment]
1.9.0

**Comment by grosser** [comment]
thx, trying that in https://github.com/grosser/soft_deletion/pull/54

**Pull request merged**
